language: python
python:
  - "3.6"
cache:
  pip: true

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: deploy
      script: mkdir artifact && tar czvf artifact/lfzyx.org.tar.gz -C _build/html .
      deploy:
        provider: pypi
        user: $user
        password: $password
        distributions: "bdist_wheel"