language: python
python:
  - "3.6"
cache:
  pip: true

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      script: python -m unittest tests/test*

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: $user
        password: $password
        distributions: "bdist_wheel"